### ISSUE TITLE
System unbootable after trying to install software

### ISSUE THREAD

**Issue by defcon8** [helloSystem/hello#468]
Hi,

I run into a strange issue. I have installed the live system to my harddrive and i'm able to boot from it. Even tested rebooting.. everything works fine at this point.

But once I try to install any application, for example "Chromium" from the menu. Then the application installer seems to finish without any error (the installer dialog disapears). But then the desktop environment is unresponsive. Whenever I now try to reboot the system, I see the gray "FreeBSD" screen and then the display turns black. At this point I can't do anything.. even switching to virtual terminals is not possible. 

The only thing it reacts to is the power button, when I hold that for a few seconds.. the screen becomes gray again and I see FreeBSD shutting down.

Besides this bug, helloSystem runs fluid on this machine. Very fast experience.. 1080p video in youtube running flawless. Audio & network also works.

Hardware:
Lenovo ThinkPad Edge S1 Yoga (model: tp00062a)
8 GB RAM
256 GB SSD

helloSystem 0.8.0

Any idea how to solve this? I am able to boot into single user mode.

**Comment by probonopd** [comment]
Please provide more details:
* Which exact build of 0.8.0? (System -> About This Computer). If older than build 0H284, then please repeat with the officially released version (which is build 0H284)
* When you are installing, click on "Show Details" and check whether anything gets uninstalled

**Comment by defcon8** [comment]
Hi @probonopd, thanks for the help I was running 0G160. The problems seems solved with 0H284. However a few things cought my attention.

- When I tried to install 0H284 on top of 0G160 the FreeBSD installer got stuck on "gpart destroy -F ada0" with an error of "gpart: arg0 'ada0': Invalid argument". Apparently gpart cannot overwrite the ZFS partition, or something like that. I manage to get around it by formatting the whole disk as ext4 using an Ubuntu live-usb stick.
- 0H284 is asking me my prefered languag on each boot on entering the graphical environment.
- The Dock (menu bar at the bottom) is gone

**Comment by probonopd** [comment]
> When I tried to install 0H284 on top of 0G160 the FreeBSD installer got stuck on "gpart destroy -F ada0" with an error of "gpart: arg0 'ada0': Invalid argument".

Interesting. We are overwriting the whole partition table with the intent to entirely solve such issues, but apparently this is still not sufficient.

> 0H284 is asking me my preferred language on each boot on entering the graphical environment.
> The Dock (menu bar at the bottom) is gone

These are features, not bugs.

If the EFI NVRAM variable `prev-lang:kbd` is set, then the language selection screen is skipped. Maybe helloSystem will write this variable automatically in the future.
